name: Dollar
image: ubuntu-14-04-x64
min_size: 1gb
config:
  #cloud-config
  users:
    - name: dollar
      groups: sudo
      shell: /bin/bash
      sudo: ['ALL=(ALL) NOPASSWD:ALL']
  packages:
    - git
  runcmd:
    - cd /home/dollar && curl -L http://dl.bintray.com/neilellis/dollar/dollar-0.1.4-904.tgz > dollar.tgz &&  tar -zxvf dollar.tgz &&  "echo 'PATH=$PATH:$HOME/dollar/bin' >> /home/dollar/.bashrc"

