defaults: &defaults
  working_directory: ~/dollar
  docker:
    - image: sillelien/circleci-dollar-build-image
    - image: redis:3-alpine

  environment:
    MAJOR_VERSION: 0.3
    MAVEN_OPTS: "-Xmx1g -DbuildNumber=${CIRCLE_BUILD_NUM} -Dorg.xml.sax.driver='com.sun.org.apache.xerces.internal.parsers.SAXParser' "
    TZ: "/usr/share/zoneinfo/Europe/London"
  branches:
    ignore:
      - gh-pages


version: 2
jobs:
    build:
      <<: *defaults

      steps:

        - checkout

        - restore_cache:
            key: dependency-cache

        - run:
            name: dependencies
            command: |
              ~/build-utils/maven_make_deps.sh

        - save_cache:
            key: dependency-cache
            paths:
                - ~/.m2
        - run:
            name: test
            command: |
                 mvn -q -T 1C -Drat.skip -Dsource.skip=true -DgenerateReports=false -Dmaven.javadoc.skip=true install
            no_output_timeout: 600


    promote:
      <<: *defaults

      steps:
        - checkout

#
#        - restore_cache:
#            key: dependency-cache

        - run:
            name: promote
            command: |
                ~/build-utils/promote_from_staging.sh

    maven-site:
      <<: *defaults

      steps:

        - checkout

        - restore_cache:
            key: dependency-cache

        - run:
            name: site
            command: |
                ~/build-utils/maven_deploy.sh


        - save_cache:
            key: dependency-cache
            paths:
                - ~/.m2


    docs:
      <<: *defaults

      steps:

        - checkout

        - restore_cache:
            key: dependency-cache

        - run:
            name: build-bdocs
            command: |
                ./build-docs.sh

        - persist_to_workspace:
            root: dist
            paths:
              - docs

        - save_cache:
            key: dependency-cache
            paths:
                - ~/.m2


    dist:
      <<: *defaults

      steps:

        - checkout

        - attach_workspace:
            at: ~/dist

        - restore_cache:
            key: dependency-cache

        - run:
            name: pack-and-upload
            command: |
                ./pack/pack.sh
                ./pack/upload.sh

        - save_cache:
            key: dependency-cache
            paths:
                - ~/.m2

        - persist_to_workspace:
            root: dist
            paths:
              - dollar

    docker:
      <<: *defaults

      steps:

        - checkout

        - attach_workspace:
            at: ~/dist

        - run:
            name: build-and-deploy
            command: |
                ./build-docker.sh
                ./deploy-docker.sh



workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - promote:
          requires:
            - build
          filters:
            branches:
              only: staging
      - maven-site:
          filters:
            branches:
              only: master
      - docs:
          filters:
            branches:
              only: master
      - dist:
          requires:
            - docs
            - maven-site
          filters:
            branches:
              only: master
      - docker:
          requires:
            - dist
          filters:
            branches:
              only: master
