defaults: &defaults
  working_directory: ~/dollar
  docker:
    - image: sillelien/circleci-dollar-build-image
    - image: redis:3-alpine

  environment:
    MAJOR_VERSION: 0.3
    NEXT_MAJOR_VERSION: 0.4
    MAVEN_OPTS: "-Xmx1g -DbuildNumber=${CIRCLE_BUILD_NUM}"
    TZ: "/usr/share/zoneinfo/Europe/London"


version: 2
jobs:
    build:
      <<: *defaults

      steps:

        - checkout

        - restore_cache:
            keys:
              - m2-build-{{ .Branch }}-{{ checksum "pom.xml" }}
              - m2-{{ .Branch }}-{{ checksum "pom.xml" }}
              - m2-{{ .Branch }}
              - m2

        - run:
            name: init
            command: /home/circleci/.build-init.sh


        - run:
            name: test
            command: bin/build.sh
            no_output_timeout: 600

        - save_cache:
            key: m2-build-{{ .Branch }}-{{ checksum "pom.xml" }}
            paths:
              - ~/.m2

        - store_test_results:
            path: dollar-examples/target/surefire-reports

#        - run:
#            name: dist-files
#            command: mkdir -p /home/circleci/workspace/ && cp -rf /home/circleci/dollar/dist /home/circleci/workspace/
#
#        - persist_to_workspace:
#            root: /home/circleci/workspace
#            paths:
#              - dist

    promote:
      <<: *defaults

      steps:
        - checkout

        - run:
            name: init
            command: /home/circleci/.build-init.sh

        - run:
            name: promote
            command: ~/build-utils/promote_from_staging.sh


    maven-deploy:
      <<: *defaults

      steps:

        - checkout

        - restore_cache:
            keys:
              - m2-deploy-{{ .Branch }}-{{ checksum "pom.xml" }}
              - m2-{{ .Branch }}-{{ checksum "pom.xml" }}
              - m2-{{ .Branch }}
              - m2

        - run:
            name: init
            command: /home/circleci/.build-init.sh

        - run:
            name: deploy
            command: bin/deploy-maven.sh

        - save_cache:
            key: m2-deploy{{ .Branch }}-{{ checksum "pom.xml" }}
            paths:
                - ~/.m2


#    docs:
#      <<: *defaults
#      docker:
#        - image: jekyll/builder
#
#      steps:
#
#        - checkout
#        - run:
#            name: build-docs
#            command: |
#              git config --global user.email "hello@neilellis.me"
#              git config --global user.name "Neil Ellis"
#              cd /srv/jekyll
#              git clone https://github.com/sillelien/dollar project
#              cd project
#              git checkout $CIRCLE_BRANCH
#              cd ..
#              mkdir -p dist
#              cd dist
#              git clone https://github.com/sillelien/dollar docs
#              cd docs
#              git checkout gh-pages
#              jekyll build --source /srv/jekyll/project/dollar-docs/src/main/webapp/ --destination /srv/jekyll/dist/docs
#              git add *
#              git commit -a -m "Updated docs from build"  || :
#              git push || :
#              cd /srv/jekyll
#
#        - persist_to_workspace:
#            root: .
#            paths:
#              - dist/docs


    devdocs:
      <<: *defaults

      steps:

        - checkout

        - restore_cache:
            keys:
              - m2-devdocs-{{ .Branch }}-{{ checksum "pom.xml" }}
              - m2-{{ .Branch }}-{{ checksum "pom.xml" }}
              - m2-{{ .Branch }}
              - m2

        - run:
            name: init
            command: /home/circleci/.build-init.sh

        - run:
            name: build-docs
            command: bin/build-devdocs.sh

        - persist_to_workspace:
            root: /home/circleci/workspace
            paths:
              - devdocs
              - gendocs

        - save_cache:
            key: m2-devdocs-{{ .Branch }}-{{ checksum "pom.xml" }}
            paths:
                - ~/.m2

        - save_cache:
            key: m2-{{ .Branch }}-{{ checksum "pom.xml" }}
            paths:
                - ~/.m2

        - save_cache:
            key: m2-{{ .Branch }}
            paths:
                - ~/.m2

        - store_test_results:
            path: dollar-docs/target/surefire-reports

        - store_artifacts:
            path: /home/circleci/workspace/gendocs/


    docs:
      <<: *defaults

      steps:

        - checkout

        - attach_workspace:
            at: /home/circleci/workspace

        - run:
            name: build-docs
            command: |
              set -ex
              git config --global user.email "hello@neilellis.me"
              git config --global user.name "Neil Ellis"
              cd docs
              rm -rf dev || :
              cp -rf /home/circleci/workspace/devdocs dev
              git add dev
              echo "release: $(cat  ../.release)" > _data/env.yml
              echo "---" >  _pages/manual.md
              echo "layout: single" >>_pages/manual.md
              echo "title:  \"Dollar Scripting Language Manual\"" >> _pages/manual.md
              echo "permalink: /manual/" >> _pages/manual.md
              echo "---" >>_pages/manual.md
              tail -n +2 /home/circleci/dollar/dollar-docs/src/main/resources/pages/manual.md | sed -E "s/\`\`\`dollar/\`\`\`/" >> _pages/manual.md
              cat  /home/circleci/workspace/gendocs/symbols.md >> _pages/manual.md
              git commit -a -m "Updated docs from build [ci skip]"  || :
              git push
              cd ..
              cp -rf /home/circleci/dollar/docs /home/circleci/workspace/docs

        - store_artifacts:
            path: /home/circleci/workspace/docs

        - persist_to_workspace:
            root: /home/circleci/workspace
            paths:
              - docs

    docs-preflight:
      <<: *defaults

      docker:
        - image: sillelien/circleci-jekyll-build-image

      steps:

        - attach_workspace:
            at: /srv/jekyll/workspace

        - run:
            name: build-docs
            command: |
              set -ex
              cd /srv/jekyll/workspace/docs
              ls -l
              bundle exec jekyll build --source /srv/jekyll/workspace/docs/ --destination /srv/jekyll/workspace/docs-built/

        - store_artifacts:
            path: /srv/jekyll/workspace/docs-built/



    dist:
      <<: *defaults

      steps:

        - checkout

        - attach_workspace:
            at: /home/circleci/workspace

        - restore_cache:
            keys:
                - m2-dist-{{ .Branch }}-{{ checksum "pom.xml" }}
                - m2-{{ .Branch }}-{{ checksum "pom.xml" }}
                - m2-{{ .Branch }}
                - m2

        - run:
            name: init
            command: /home/circleci/.build-init.sh


        - run:
            name: build-dist
            command: bin/build-dist.sh

        - run:
            name: test-dist
            command: |
              git config --global --unset url."ssh://git@github.com".insteadOf "https://github.com" || true
              bin/test-dist.sh
              git config --global url."ssh://git@github.com".insteadOf "https://github.com" || true

        - run:
            name: deploy-dist
            command: bin/deploy-dist.sh

        - save_cache:
            key: m2-dist-{{ .Branch }}-{{ checksum "pom.xml" }}
            paths:
                - ~/.m2

        - save_cache:
            key: m2-{{ .Branch }}-{{ checksum "pom.xml" }}
            paths:
                - ~/.m2

        - save_cache:
            key: m2-{{ .Branch }}
            paths:
                - ~/.m2

        - save_cache:
            key: m2
            paths:
                - ~/.m2

        - persist_to_workspace:
            root: /home/circleci/workspace
            paths:
              - dist
              - devdocs
              - artifacts

        - store_artifacts:
            path: /home/circleci/workspace/artifacts/

    docker:
      <<: *defaults

      steps:

        - checkout

        - run:
            name: init
            command: /home/circleci/.build-init.sh

        - attach_workspace:
            at: /home/circleci/workspace

        - setup_remote_docker

        - run:
            name: build
            command:  bin/build-docker.sh

        - run:
            name: test
            command:  "bin/test-docker.sh || :"

        - run:
            name: deploy
            command:  bin/deploy-docker.sh



    finish:
      <<: *defaults

      steps:

        - checkout

        - run:
            name: init
            command: /home/circleci/.build-init.sh

        - run:
            name: finish
            command:  /home/circleci/build-utils/finish-deploy.sh



workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages

      - devdocs:
          filters:
            branches:
              ignore:
                - gh-pages
                - dev

      - docs:
          requires:
            - devdocs
            - dist
            - maven-deploy
          filters:
            branches:
              only:
                - master

      - docs-preflight:
          requires:
            - docs
          filters:
            branches:
              only:
                - master

      - maven-deploy:
          requires:
            - build
            - devdocs
          filters:
            branches:
              only: master

      - promote:
          requires:
            - build
            - devdocs
          filters:
            branches:
              only: staging

      - dist:
          requires:
            - build
            - devdocs
          filters:
            branches:
              only: master

      - docker:
          requires:
            - dist
          filters:
            branches:
              only: master

      - finish:
          requires:
            - docker
            - dist
            - docs
            - build
            - devdocs
            - maven-deploy
            - docs-preflight
          filters:
            branches:
              only: master
