defaults: &defaults
  working_directory: ~/dollar
  docker:
    - image: sillelien/circleci-dollar-build-image
    - image: redis:3-alpine

  environment:
    MAJOR_VERSION: 0.3
    MAVEN_OPTS: "-Xmx1g -DbuildNumber=${CIRCLE_BUILD_NUM} -Dorg.xml.sax.driver='com.sun.org.apache.xerces.internal.parsers.SAXParser' "
    TZ: "/usr/share/zoneinfo/Europe/London"
  branches:
    ignore:
      - gh-pages


version: 2
jobs:
    build:
      <<: *defaults

      steps:

        - checkout

        - restore_cache:
            key: dependency-cache

        - run:
            name: dependencies
            command: |
              ~/build-utils/maven_make_deps.sh

        - save_cache:
            key: dependency-cache
            paths:
                - ~/.m2
        - run:
            name: test
            command: ./build.sh

            no_output_timeout: 600

    promote:
      <<: *defaults

      steps:
        - checkout
        - run:
            name: promote
            command: ~/build-utils/promote_from_staging.sh

    maven-deploy:
      <<: *defaults

      steps:

        - checkout

        - restore_cache:
            key: dependency-cache

        - run:
            name: site
            command: |
                ./deploy-maven.sh

        - save_cache:
            key: dependency-cache
            paths:
                - ~/.m2


    docs:
      <<: *defaults

      steps:

        - checkout

        - restore_cache:
            key: dependency-cache

        - run:
            name: build-bdocs
            command: |
                ./build-docs.sh

        - persist_to_workspace:
            root: .
            paths:
              - dist/docs

        - save_cache:
            key: dependency-cache
            paths:
                - ~/.m2


    dist:
      <<: *defaults

      steps:

        - checkout

        - attach_workspace:
            at: dist/docs

        - restore_cache:
            key: dependency-cache

        - run:
            name: build-dist
            command: |
                ./build-dist.sh

        - run:
            name: test-dist
            command: |
                ./test-dist.sh

        - run:
            name: upload-dist
            command: |
                ./deploy-dist.sh

        - save_cache:
            key: dependency-cache
            paths:
                - ~/.m2

        - persist_to_workspace:
            root: .
            paths:
              - dist/dollar

    docker:
      <<: *defaults

      steps:

        - checkout

        - attach_workspace:
            at: dist/dollar

        - run:
            name: build-and-deploy
            command: |
                ./build-docker.sh
                ./deploy-docker.sh



workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - docs:
          requires:
            - build
      - maven-deploy:
          requires:
            - build
            - docs
          filters:
            branches:
              only: master
      - promote:
          requires:
            - build
            - docs
          filters:
            branches:
              only: staging
      - dist:
          requires:
            - build
            - docs
          filters:
            branches:
              only: master
      - docker:
          requires:
            - dist
          filters:
            branches:
              only: master
