defaults: &defaults
  working_directory: /tmp
  docker:
    - image: sillelien/circleci-dollar-build-image
    - image: redis:3-alpine

  environment:
    MAJOR_VERSION: 0.3
    MAVEN_OPTS: "-Xmx1g -DbuildNumber=${CIRCLE_BUILD_NUM} -Dorg.xml.sax.driver='com.sun.org.apache.xerces.internal.parsers.SAXParser' "
    TZ: "/usr/share/zoneinfo/Europe/London"
  branches:
    ignore:
      - gh-pages


version: 2
jobs:
    build:
      <<: *defaults

      steps:

        - checkout

        - restore_cache:
            key: dependency-cache

        - run:
            name: dependencies
            command: |
              ~/build-utils/maven_make_deps.sh

        - save_cache:
            key: dependency-cache
            paths:
                - ~/.gnupg
                - ~/.m2
        - run:
            name: test
            command: |
                 mvn -q -T 1C -Drat.skip -Dsource.skip=true -DgenerateReports=false -Dmaven.javadoc.skip=true install
            no_output_timeout: 600

   promote:
      <<: *defaults

      steps:

        - checkout

        - restore_cache:
            key: dependency-cache

        - run:
            name: promote
            command: |
                ~/build-utils/promote_from_staging.sh

    deploy:
      <<: *defaults

      steps:

        - checkout

        - restore_cache:
            key: dependency-cache

        - run:
            name: test
            command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                ~/build-utils/maven_deploy.sh
                ./build-docs.sh
                ./pack/pack.sh
                ./pack/upload.sh
              fi

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - promote:
          requires:
            - build
          filters:
            branches:
              only: staging
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
