defaults: &defaults
  working_directory: ~/dollar
  docker:
    - image: sillelien/circleci-dollar-build-image
    - image: redis:3-alpine

  environment:
    MAJOR_VERSION: 0.3
    MAVEN_OPTS: "-Xmx1g -DbuildNumber=${CIRCLE_BUILD_NUM} -Dorg.xml.sax.driver='com.sun.org.apache.xerces.internal.parsers.SAXParser' "
    TZ: "/usr/share/zoneinfo/Europe/London"


version: 2
jobs:
    build:
      <<: *defaults

      steps:

        - checkout

        - restore_cache:
            key: dependency-cache

        - run:
            name: dependencies
            command: ~/build-utils/maven_make_deps.sh

        - save_cache:
            key: dependency-cache
            paths:
                - ~/.m2
        - run:
            name: test
            command: ./build.sh

            no_output_timeout: 600

    promote:
      <<: *defaults

      steps:
        - checkout
        - run:
            name: promote
            command: ~/build-utils/promote_from_staging.sh

    maven-deploy:
      <<: *defaults

      steps:

        - checkout

        - restore_cache:
            key: dependency-cache

        - run:
            name: deploy
            command: ./deploy-maven.sh

        - save_cache:
            key: dependency-cache
            paths:
                - ~/.m2


    docs:
      <<: *defaults
      docker:
        - image: jekyll/builder

      steps:

        - checkout
        - run:
            name: build-docs
            command: |
              git config --global user.email "hello@neilellis.me"
              git config --global user.name "Neil Ellis"
              cd /srv/jekyll
              git clone https://github.com/sillelien/dollar project
              cd project
              git checkout $CIRCLE_BRANCH
              cd ..
              mkdir -p dist
              cd dist
              git clone https://github.com/sillelien/dollar docs
              cd docs
              git checkout gh-pages
              jekyll build --source /srv/jekyll/project/dollar-docs/src/main/webapp/ --destination /srv/jekyll/dist/docs
              git add *
              git commit -a -m "Updated docs from build"  || :
              git push || :
              cd /srv/jekyll

        - persist_to_workspace:
            root: .
            paths:
              - dist/docs


    devdocs:
      <<: *defaults

      steps:

        - checkout

        - restore_cache:
            key: dependency-cache

        - run:
            name: build-docs
            command: |
              mkdir -p dist/devdocs
              ./set-version.sh
              mvn -q -Dmaven.test.skip -DskipDeploy -DstagingDirectory=dist/devdocs/ install site:site site:stage

        - persist_to_workspace:
            root: .
            paths:
              - dist/devdocs

        - save_cache:
            key: dependency-cache
            paths:
                - ~/.m2


    docs:
      <<: *defaults
      docker:
        - image: sillelien/circleci-jekyll-build-image

      steps:
        - checkout

        - attach_workspace:
            at: dist/devdocs

        - run:
            name: build-docs
            command: |
              set -x
              git config --global user.email "hello@neilellis.me"
              git config --global user.name "Neil Ellis"
              cd /srv/jekyll
              git clone https://github.com/sillelien/dollar project
              cd project
              git checkout $CIRCLE_BRANCH
              cd ..
              mkdir -p dist
              cd dist
              git clone https://github.com/sillelien/dollar docs
              cd docs
              git checkout gh-pages
              cp -rf $HOME/dollar/dist/devdocs dev
              jekyll build --source /srv/jekyll/project/dollar-docs/src/main/webapp/ --destination /srv/jekyll/dist/docs
              git add *
              git commit -a -m "Updated docs from build"  || :
              git push || :
              cd /srv/jekyll

    dist:
      <<: *defaults

      steps:

        - checkout

        - attach_workspace:
            at: dist/docs

        - attach_workspace:
            at: dist/devdocs

        - restore_cache:
            key: dependency-cache

        - run:
            name: build-dist
            command: ./build-dist.sh

        - run:
            name: test-dist
            command: |
              git config --global --unset url."ssh://git@github.com".insteadOf "https://github.com" || true
              ./test-dist.sh
              git config --global url."ssh://git@github.com".insteadOf "https://github.com" || true

        - run:
            name: upload-dist
            command: ./deploy-dist.sh

        - save_cache:
            key: dependency-cache
            paths:
                - ~/.m2

        - persist_to_workspace:
            root: .
            paths:
              - dist/dollar

    docker:
      <<: *defaults

      steps:

        - checkout

        - attach_workspace:
            at: dist/dollar

        - attach_workspace:
            at: dist/devdocs

        - run:
            name: build
            command:  ./build-docker.sh

        - run:
            name: deploy
            command:  ./deploy-docker.sh


workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages

      - devdocs:
          filters:
            branches:
              ignore:
                - gh-pages
                - dev

      - docs:
          requires:
            - devdocs
          filters:
            branches:
              ignore:
                - gh-pages
                - dev

      - maven-deploy:
          requires:
            - build
            - docs
          filters:
            branches:
              only: master

      - promote:
          requires:
            - build
            - docs
          filters:
            branches:
              only: staging

      - dist:
          requires:
            - build
            - docs
          filters:
            branches:
              only: master

      - docker:
          requires:
            - dist
          filters:
            branches:
              only: master
