# Site settings
title: Dollar
email: hello@neilellis.me
description: > # this means to ignore newlines until "baseurl:"
  DollarScript and the DollarAPI - getting things done on the JVM.
baseurl: "/dollar/" # the subpath of your site, e.g. /blog/
url: "http://sillelien.github.io/"
twitter_username: neilellis
github_username:  sillelien

# Build settings
markdown: kramdown

defaults:
  scope:
    path: ""
  values:
    comments: false

